AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: slackbot for harvest
Resources:
  TimeTrackerBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: ruby2.5
      CodeUri: s3://rajat-time-tracker-bot/1b023ddc6aabfe536021963d7bff32de
      MemorySize: 512
      Timeout: 30
      Events:
        SinatraApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: SinatraAPI
  SinatraAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: SinatraAPI
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        basePath: /
        info:
          title:
            Ref: AWS::StackName
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TimeTrackerBotFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
          /:
            post:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TimeTrackerBotFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
  ConfigLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - TimeTrackerBotFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: TimeTrackerBotFunction
      Principal: apigateway.amazonaws.com
Outputs:
  TimeTrackerBotFunction:
    Description: Launch Harvest Lambda Function ARN
    Value:
      Fn::GetAtt:
      - TimeTrackerBotFunction
      - Arn
  SinatraAppUrl:
    Description: App endpoint URL
    Value:
      Fn::Sub: https://${SinatraAPI}.execute-api.${AWS::Region}.amazonaws.com/
